name: Branch Prefix Check

on:
  pull_request:
    branches:
      - staging
      - master
    types:
      - opened
      - synchronize

jobs:
  check_prefix:
    name: Runner Check
    runs-on: ubuntu-latest
    steps:
      - name: Check Branch Prefix
        uses: deepakputhraya/action-branch-name@master
        with:
          regex: '([a-z])+/.*'
          allowed_prefixes: 'master,staging,feature/,bugfix/,hotfix/,bug/,fix/,topic/,dependabot'
          ignore: 'false'
          min_length: 5
          max_length: 200
